ALTER TABLE delivery_attempts
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN metadata   TEXT        NOT NULL DEFAULT '{}';
