name: Shared

on:
  push:
    branches: [master]
    paths:
      - "shared/**"
      - ".golangci.yml"
      - ".github/workflows/shared.yml"
  pull_request:
    branches: [master]
    paths:
      - "shared/**"
      - ".golangci.yml"
      - ".github/workflows/shared.yml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: shared/go.mod
          cache: false

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-shared-${{ runner.os }}-${{ hashFiles('shared/go.sum') }}
          restore-keys: go-shared-${{ runner.os }}-

      - run: make install-tools
      - run: make lint-shared

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: shared/go.mod
          cache: false

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-shared-${{ runner.os }}-${{ hashFiles('shared/go.sum') }}
          restore-keys: go-shared-${{ runner.os }}-

      - run: make install-tools
      - run: make test-shared
